//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/Input Provider/Player Actions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Lamplight.Input
{
    public partial class @PlayerActions : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @PlayerActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""Player Actions"",
    ""maps"": [
        {
            ""name"": ""GameActions"",
            ""id"": ""601b18d7-e647-4394-9a7d-42ccc0e88156"",
            ""actions"": [
                {
                    ""name"": ""Look"",
                    ""type"": ""PassThrough"",
                    ""id"": ""d01dd5da-dfad-4e78-964e-1aff8f42f897"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""PassThrough"",
                    ""id"": ""575313ea-6e51-410f-b3e4-04158dad9df3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""NormalizeVector2"",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""4d987de4-cb57-49ad-984a-e4ede96d9454"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""5e839a2a-f46c-4df1-b61e-5617e42db436"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""0c23bc82-7ae0-4d14-9290-93dcb8c6c9aa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Whistle"",
                    ""type"": ""Button"",
                    ""id"": ""32187f05-bf04-4d2a-a192-2d929544c570"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""11b3bc5b-5cf8-48a1-980d-c46527f0cb17"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LockTarget"",
                    ""type"": ""Button"",
                    ""id"": ""53af0961-edbb-4cb2-a49b-140aef45116e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Aim"",
                    ""type"": ""Button"",
                    ""id"": ""373b581c-f9b7-4523-b081-910727e50b26"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""9402a7db-b683-47fa-a80c-cbebae4ffb48"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseItem"",
                    ""type"": ""Button"",
                    ""id"": ""8d4bbd85-cc7f-4559-a7d1-d8a386eaa7c6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Menu"",
                    ""type"": ""Button"",
                    ""id"": ""bd60299e-686e-4513-b95d-a1a633c90525"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Inventory"",
                    ""type"": ""Button"",
                    ""id"": ""370f956f-50bd-485a-bbc8-c44b811ba4d3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Light"",
                    ""type"": ""Button"",
                    ""id"": ""62f5e918-8cfa-4ddc-a753-afdc071480a4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""af30af03-57ea-4e28-9b0b-b8daccc519fd"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dcdbea41-a10c-444b-a8ec-9e413680d79d"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""485a05ec-8c6b-4104-914d-e80bdaeb0e92"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""66987d8d-9cf7-4a2b-91e0-50354253279e"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""84f2e09a-5122-4544-8100-17f61119dba6"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""aeb377b8-9cad-4a11-89c4-c1b28e1f4928"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""f4526fb2-2262-41a5-a956-46e13e4741c5"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""941fd464-abaf-498d-b632-870e9dd105e5"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0f8a57df-0a09-4e27-9a1c-e681705e707f"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a73dc74e-0ee4-4b1b-a512-8af80e2a44d3"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1448e60-839f-4232-916c-0c97eb6eff4a"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""22019dce-edb3-44d7-9e5c-ec78ab65427e"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d51bc289-9362-417a-bc57-585b1a973ed2"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Whistle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""63400bd6-18a8-41b6-b716-a372f99995fc"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Whistle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2f974de4-fc23-4025-873c-4a9990ebac9f"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3a155832-00b1-4a1e-86d3-a7629adafb98"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7a825b88-f253-4fd3-b77f-89e0b6b2cbbe"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LockTarget"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0b99b155-be09-4ec9-a40d-f763305d0137"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LockTarget"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""db8bed11-36b3-41e0-ae3b-dd4ab89e45bb"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""063ab3d8-9c5d-47f4-b2ad-58c8cb01a395"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1665c5e-f637-4ffd-8003-8a200c972343"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""092f61e4-1fcd-4962-8aee-1dcf6aa03abc"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9036c25e-e6e1-42e3-ab88-abe9a164c028"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1ab7c92d-a36e-42fb-852f-02191fa0112e"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""db22f24a-6c4a-4f96-80c5-7a8d54df85c8"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9e8f9023-6793-482e-ac67-ed1a9c8fee1b"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8900c54b-55c5-43ca-83c1-1cadaa696fcc"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ba9614cf-4418-430f-9f78-2ba9f0bc95c7"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""50ba8165-0421-4ba2-b890-68d49a907cff"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9ca40a11-a9e3-4244-bfdb-1b5ec11872bd"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8c7fbc10-7531-4600-9a3d-ab08947ade48"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Light"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""128698a4-ba08-4c5e-858a-528ac6a12c8f"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Light"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // GameActions
            m_GameActions = asset.FindActionMap("GameActions", throwIfNotFound: true);
            m_GameActions_Look = m_GameActions.FindAction("Look", throwIfNotFound: true);
            m_GameActions_Move = m_GameActions.FindAction("Move", throwIfNotFound: true);
            m_GameActions_Jump = m_GameActions.FindAction("Jump", throwIfNotFound: true);
            m_GameActions_Sprint = m_GameActions.FindAction("Sprint", throwIfNotFound: true);
            m_GameActions_Crouch = m_GameActions.FindAction("Crouch", throwIfNotFound: true);
            m_GameActions_Whistle = m_GameActions.FindAction("Whistle", throwIfNotFound: true);
            m_GameActions_Interact = m_GameActions.FindAction("Interact", throwIfNotFound: true);
            m_GameActions_LockTarget = m_GameActions.FindAction("LockTarget", throwIfNotFound: true);
            m_GameActions_Aim = m_GameActions.FindAction("Aim", throwIfNotFound: true);
            m_GameActions_Attack = m_GameActions.FindAction("Attack", throwIfNotFound: true);
            m_GameActions_UseItem = m_GameActions.FindAction("UseItem", throwIfNotFound: true);
            m_GameActions_Menu = m_GameActions.FindAction("Menu", throwIfNotFound: true);
            m_GameActions_Inventory = m_GameActions.FindAction("Inventory", throwIfNotFound: true);
            m_GameActions_Light = m_GameActions.FindAction("Light", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // GameActions
        private readonly InputActionMap m_GameActions;
        private IGameActionsActions m_GameActionsActionsCallbackInterface;
        private readonly InputAction m_GameActions_Look;
        private readonly InputAction m_GameActions_Move;
        private readonly InputAction m_GameActions_Jump;
        private readonly InputAction m_GameActions_Sprint;
        private readonly InputAction m_GameActions_Crouch;
        private readonly InputAction m_GameActions_Whistle;
        private readonly InputAction m_GameActions_Interact;
        private readonly InputAction m_GameActions_LockTarget;
        private readonly InputAction m_GameActions_Aim;
        private readonly InputAction m_GameActions_Attack;
        private readonly InputAction m_GameActions_UseItem;
        private readonly InputAction m_GameActions_Menu;
        private readonly InputAction m_GameActions_Inventory;
        private readonly InputAction m_GameActions_Light;
        public struct GameActionsActions
        {
            private @PlayerActions m_Wrapper;
            public GameActionsActions(@PlayerActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Look => m_Wrapper.m_GameActions_Look;
            public InputAction @Move => m_Wrapper.m_GameActions_Move;
            public InputAction @Jump => m_Wrapper.m_GameActions_Jump;
            public InputAction @Sprint => m_Wrapper.m_GameActions_Sprint;
            public InputAction @Crouch => m_Wrapper.m_GameActions_Crouch;
            public InputAction @Whistle => m_Wrapper.m_GameActions_Whistle;
            public InputAction @Interact => m_Wrapper.m_GameActions_Interact;
            public InputAction @LockTarget => m_Wrapper.m_GameActions_LockTarget;
            public InputAction @Aim => m_Wrapper.m_GameActions_Aim;
            public InputAction @Attack => m_Wrapper.m_GameActions_Attack;
            public InputAction @UseItem => m_Wrapper.m_GameActions_UseItem;
            public InputAction @Menu => m_Wrapper.m_GameActions_Menu;
            public InputAction @Inventory => m_Wrapper.m_GameActions_Inventory;
            public InputAction @Light => m_Wrapper.m_GameActions_Light;
            public InputActionMap Get() { return m_Wrapper.m_GameActions; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(GameActionsActions set) { return set.Get(); }
            public void SetCallbacks(IGameActionsActions instance)
            {
                if (m_Wrapper.m_GameActionsActionsCallbackInterface != null)
                {
                    @Look.started -= m_Wrapper.m_GameActionsActionsCallbackInterface.OnLook;
                    @Look.performed -= m_Wrapper.m_GameActionsActionsCallbackInterface.OnLook;
                    @Look.canceled -= m_Wrapper.m_GameActionsActionsCallbackInterface.OnLook;
                    @Move.started -= m_Wrapper.m_GameActionsActionsCallbackInterface.OnMove;
                    @Move.performed -= m_Wrapper.m_GameActionsActionsCallbackInterface.OnMove;
                    @Move.canceled -= m_Wrapper.m_GameActionsActionsCallbackInterface.OnMove;
                    @Jump.started -= m_Wrapper.m_GameActionsActionsCallbackInterface.OnJump;
                    @Jump.performed -= m_Wrapper.m_GameActionsActionsCallbackInterface.OnJump;
                    @Jump.canceled -= m_Wrapper.m_GameActionsActionsCallbackInterface.OnJump;
                    @Sprint.started -= m_Wrapper.m_GameActionsActionsCallbackInterface.OnSprint;
                    @Sprint.performed -= m_Wrapper.m_GameActionsActionsCallbackInterface.OnSprint;
                    @Sprint.canceled -= m_Wrapper.m_GameActionsActionsCallbackInterface.OnSprint;
                    @Crouch.started -= m_Wrapper.m_GameActionsActionsCallbackInterface.OnCrouch;
                    @Crouch.performed -= m_Wrapper.m_GameActionsActionsCallbackInterface.OnCrouch;
                    @Crouch.canceled -= m_Wrapper.m_GameActionsActionsCallbackInterface.OnCrouch;
                    @Whistle.started -= m_Wrapper.m_GameActionsActionsCallbackInterface.OnWhistle;
                    @Whistle.performed -= m_Wrapper.m_GameActionsActionsCallbackInterface.OnWhistle;
                    @Whistle.canceled -= m_Wrapper.m_GameActionsActionsCallbackInterface.OnWhistle;
                    @Interact.started -= m_Wrapper.m_GameActionsActionsCallbackInterface.OnInteract;
                    @Interact.performed -= m_Wrapper.m_GameActionsActionsCallbackInterface.OnInteract;
                    @Interact.canceled -= m_Wrapper.m_GameActionsActionsCallbackInterface.OnInteract;
                    @LockTarget.started -= m_Wrapper.m_GameActionsActionsCallbackInterface.OnLockTarget;
                    @LockTarget.performed -= m_Wrapper.m_GameActionsActionsCallbackInterface.OnLockTarget;
                    @LockTarget.canceled -= m_Wrapper.m_GameActionsActionsCallbackInterface.OnLockTarget;
                    @Aim.started -= m_Wrapper.m_GameActionsActionsCallbackInterface.OnAim;
                    @Aim.performed -= m_Wrapper.m_GameActionsActionsCallbackInterface.OnAim;
                    @Aim.canceled -= m_Wrapper.m_GameActionsActionsCallbackInterface.OnAim;
                    @Attack.started -= m_Wrapper.m_GameActionsActionsCallbackInterface.OnAttack;
                    @Attack.performed -= m_Wrapper.m_GameActionsActionsCallbackInterface.OnAttack;
                    @Attack.canceled -= m_Wrapper.m_GameActionsActionsCallbackInterface.OnAttack;
                    @UseItem.started -= m_Wrapper.m_GameActionsActionsCallbackInterface.OnUseItem;
                    @UseItem.performed -= m_Wrapper.m_GameActionsActionsCallbackInterface.OnUseItem;
                    @UseItem.canceled -= m_Wrapper.m_GameActionsActionsCallbackInterface.OnUseItem;
                    @Menu.started -= m_Wrapper.m_GameActionsActionsCallbackInterface.OnMenu;
                    @Menu.performed -= m_Wrapper.m_GameActionsActionsCallbackInterface.OnMenu;
                    @Menu.canceled -= m_Wrapper.m_GameActionsActionsCallbackInterface.OnMenu;
                    @Inventory.started -= m_Wrapper.m_GameActionsActionsCallbackInterface.OnInventory;
                    @Inventory.performed -= m_Wrapper.m_GameActionsActionsCallbackInterface.OnInventory;
                    @Inventory.canceled -= m_Wrapper.m_GameActionsActionsCallbackInterface.OnInventory;
                    @Light.started -= m_Wrapper.m_GameActionsActionsCallbackInterface.OnLight;
                    @Light.performed -= m_Wrapper.m_GameActionsActionsCallbackInterface.OnLight;
                    @Light.canceled -= m_Wrapper.m_GameActionsActionsCallbackInterface.OnLight;
                }
                m_Wrapper.m_GameActionsActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Look.started += instance.OnLook;
                    @Look.performed += instance.OnLook;
                    @Look.canceled += instance.OnLook;
                    @Move.started += instance.OnMove;
                    @Move.performed += instance.OnMove;
                    @Move.canceled += instance.OnMove;
                    @Jump.started += instance.OnJump;
                    @Jump.performed += instance.OnJump;
                    @Jump.canceled += instance.OnJump;
                    @Sprint.started += instance.OnSprint;
                    @Sprint.performed += instance.OnSprint;
                    @Sprint.canceled += instance.OnSprint;
                    @Crouch.started += instance.OnCrouch;
                    @Crouch.performed += instance.OnCrouch;
                    @Crouch.canceled += instance.OnCrouch;
                    @Whistle.started += instance.OnWhistle;
                    @Whistle.performed += instance.OnWhistle;
                    @Whistle.canceled += instance.OnWhistle;
                    @Interact.started += instance.OnInteract;
                    @Interact.performed += instance.OnInteract;
                    @Interact.canceled += instance.OnInteract;
                    @LockTarget.started += instance.OnLockTarget;
                    @LockTarget.performed += instance.OnLockTarget;
                    @LockTarget.canceled += instance.OnLockTarget;
                    @Aim.started += instance.OnAim;
                    @Aim.performed += instance.OnAim;
                    @Aim.canceled += instance.OnAim;
                    @Attack.started += instance.OnAttack;
                    @Attack.performed += instance.OnAttack;
                    @Attack.canceled += instance.OnAttack;
                    @UseItem.started += instance.OnUseItem;
                    @UseItem.performed += instance.OnUseItem;
                    @UseItem.canceled += instance.OnUseItem;
                    @Menu.started += instance.OnMenu;
                    @Menu.performed += instance.OnMenu;
                    @Menu.canceled += instance.OnMenu;
                    @Inventory.started += instance.OnInventory;
                    @Inventory.performed += instance.OnInventory;
                    @Inventory.canceled += instance.OnInventory;
                    @Light.started += instance.OnLight;
                    @Light.performed += instance.OnLight;
                    @Light.canceled += instance.OnLight;
                }
            }
        }
        public GameActionsActions @GameActions => new GameActionsActions(this);
        public interface IGameActionsActions
        {
            void OnLook(InputAction.CallbackContext context);
            void OnMove(InputAction.CallbackContext context);
            void OnJump(InputAction.CallbackContext context);
            void OnSprint(InputAction.CallbackContext context);
            void OnCrouch(InputAction.CallbackContext context);
            void OnWhistle(InputAction.CallbackContext context);
            void OnInteract(InputAction.CallbackContext context);
            void OnLockTarget(InputAction.CallbackContext context);
            void OnAim(InputAction.CallbackContext context);
            void OnAttack(InputAction.CallbackContext context);
            void OnUseItem(InputAction.CallbackContext context);
            void OnMenu(InputAction.CallbackContext context);
            void OnInventory(InputAction.CallbackContext context);
            void OnLight(InputAction.CallbackContext context);
        }
    }
}
